name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake \
            libffi-dev libssl-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libfreetype6-dev libjpeg-dev libpng-dev libsqlite3-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev

      - name: Install Buildozer & Tools
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer
          pip3 install Cython==0.29.33 virtualenv

      - name: Build APK
        run: |
          sudo apt-get install -y libtinfo6
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: studentdetailsapp-debug.apk
          path: bin/*.apk
