name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk python3-pip \
            libfreetype6-dev libpng-dev libz-dev \
            libffi-dev build-essential \
            libsqlite3-dev libjpeg-dev git \
            libgl1-mesa-dev libblas-dev liblapack-dev \
            wget

          pip install --upgrade pip setuptools wheel Cython==0.29.36
          pip install buildozer==1.5.0

      - name: Install Android SDK Tools (Fix AIDL)
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk
          cd $HOME/.buildozer/android/platform/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses
          cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.1.8937393" "cmake;3.10.2.4988404"

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: studentdetailsapp-debug.apk
          path: bin/*.apk
