name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libtinfo6 \
            zlib1g-dev \
            libncurses5

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools Cython virtualenv
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          buildozer android clean
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: studentmanager-apk
          path: bin/*.apk
