name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk python3-pip \
            libfreetype6-dev libpng-dev libz-dev \
            libffi-dev build-essential \
            libsqlite3-dev libjpeg-dev

          pip install --upgrade pip setuptools wheel Cython==0.29.36
          pip install buildozer==1.5.0

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: studentdetailsapp-debug.apk
          path: bin/*.apk
