name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3 \
            python3-pip \
            libfreetype6-dev \
            libffi-dev \
            libjpeg-dev \
            libpng-dev \
            libsqlite3-dev \
            libSDL2-dev \
            libtiff5-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libmtdev-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            xclip \
            xsel \
            libjpeg-dev \
            libpython3-dev \
            python3-setuptools \
            python3-wheel \
            python3-virtualenv \
            cython \
            libxml2-dev \
            libxslt1-dev \
            liblzma-dev \
            libgirepository1.0-dev \
            libcairo2-dev

      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer
          pip3 install cython

      - name: Download Android SDK & NDK
        run: |
          sudo apt install -y libtinfo6
          buildozer android clean
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: studentdetailsapp-debug.apk
          path: bin/*.apk
