name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y libunwind-dev  # ✅ Fix dependency issue
          sudo apt-get install -y \
            build-essential \
            ccache \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libandroid-support-dev \
            libfreetype6-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libgstreamer1.0-dev \
            libmtdev-dev \
            libgl1-mesa-dev \
            git \
            python3-pip \
            unzip \
            openjdk-17-jdk

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Accept Android SDK Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: studentdetailsapp-apk
          path: bin/*.apk
